### ISSUE TITLE
bak.py won't start

### ISSUE THREAD

**Issue by mattherr** [azerothcore/telegram-automated-db-backup#1]
I tried to start the bak.py many times now and I already reinstalled everything:

Traceback (most recent call last):
  File "bak.py", line 1, in <module>
    from pyrogram import Client, Filters
ImportError: cannot import name 'Filters' from 'pyrogram' (/usr/local/lib/python3.8/dist-packages/pyrogram/__init__.py)

**Comment by mattherr** [comment]
Solution: https://github.com/DevCores/telegram-automated-db-backup/commit/a402664f1d28404a566d9973a3cf050abfea675f

**Comment by FrancescoBorzi** [comment]
@mattherr why closing this? the solution has not been merged into the master branch of this repo yet. Can you please send a PR?

**Comment by Helias** [comment]
I do not encounter this issue :/
