### ISSUE TITLE
MariaDB Support Question

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/telegram-automated-db-backup#3]
Hey! Can you please tell me if this is compatible with MariaDB?

**Comment by Helias** [comment]
It's compatible with mysql so I think that is compatible even with MariaDB. To be 100% sure you only need to test this command:
```bash
mysqldump --no-tablespaces --column-statistics=0 -h localhost -u root -p
```

Anyways, I stronlgy think that it is compatible, if not you only need to find a command that make the sql backup and replace the current one with the MariaDB one.

**Comment by PivanDepolo** [comment]
> It's compatible with mysql so I think that is compatible even with MariaDB. To be 100% sure you only need to test this command:
> 
> ```shell
> mysqldump --no-tablespaces --column-statistics=0 -h localhost -u root -p
> ```
> 
> Anyways, I stronlgy think that it is compatible, if not you only need to find a command that make the sql backup and replace the current one with the MariaDB one.

Thank you for your reply! I wanna use try your script to backup not AC databases.

**Comment by Helias** [comment]
Close this issue if you verify that everything is ok 👍

**Comment by PivanDepolo** [comment]
> Close this issue if you verify that everything is ok 👍

Sorry for the stupid question. It is not necessary to indicate the root user? Can I use my user, right?

**Comment by Helias** [comment]
you can user whatever user you want with the right privileges/permissions

**Comment by PivanDepolo** [comment]
mysqldump: unknown variable 'column-statistics=0'

**Comment by PivanDepolo** [comment]
With this -> `os.system("mysqldump -h {} -u {} -p'{}' {} > dbname.sql".format(` working good.

**Comment by Helias** [comment]
Perfect, thanks for reporting it ;-)
