### ISSUE TITLE
Suggestion: Backup files too

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/telegram-automated-db-backup#4]
Hello, @Helias  I suggest if you have free time and a desire to add a backup of files to this script

**Comment by Helias** [comment]
what do you mean? backup of the file of the PC? so a conf variable that allows you to specify a directory to zip and push to Telegram?
That would be a good feature indeed

**Comment by PivanDepolo** [comment]
> what do you mean? backup of the file of the PC? so a conf variable that allows you to specify a directory to zip and push to Telegram? That would be a good feature indeed

Yes sir. For backup files and sending not only the database, but files too

**Comment by Helias** [comment]
it's easy to make it, you only need to change the bash script in the python file, you can add it by:
```python
os.system("zip -r new-file.zip path/of/the/directory/")
```
then send also the `new-file.zip` via `sendDocument`, read the source code, it's quite simple 👍
