### ISSUE TITLE
Running on mariadb - Ubuntu 20.04

### ISSUE THREAD

**Issue by auguzsto** [azerothcore/telegram-automated-db-backup#5]
**Error**

> unknown variable 'column-statistics=0'

**Reason**

> The problem is that MariaDB doesn't support the `column-statistics` command.

**Solution**

> To resolve this error, simply remove the `column-statistics` command from the line in the bak.py file. Backup is done normally.

**Comment by Helias** [comment]
If removing the column-statistics does not affect the MySQL compatibility, we could remove it permanently

**Comment by auguzsto** [comment]
I will check this and then get back to you.
